spring:
  application:
    name: PackageService
  profiles:
    active: dev
  cloud:
    config:
      import-check:
        enabled: false

  datasource:
    url: jdbc:postgresql://localhost:5432/bonvoyage
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 4003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka